import { IGender } from '@shared/interfaces';

export const firstNames: Record<IGender, string[]> = {
  men: [
    'James',
    'John',
    'Robert',
    'Michael',
    'William',
    'David',
    'Richard',
    'Joseph',
    'Thomas',
    'Charles',
    'Christopher',
    'Daniel',
    'Matthew',
    'Anthony',
    'Mark',
    'Donald',
    'Steven',
    'Paul',
    'Andrew',
    'Joshua',
  ],
  women: [
    'Mary',
    'Patricia',
    'Jennifer',
    'Linda',
    'Elizabeth',
    'Barbara',
    'Susan',
    'Jessica',
    'Sarah',
    'Karen',
    'Nancy',
    'Lisa',
    'Margaret',
    'Betty',
    'Sandra',
    'Ashley',
    'Kimberly',
    'Emily',
    'Donna',
    'Michelle',
  ],
};
